# To access this on Streamlit consult the documentation about Secrets
# https://docs.streamlit.io/streamlit-community-cloud/get-started/deploy-an-app/connect-to-data-sources/secrets-management\
# The following above here are accessible as environment variables.

# Discord Webhook for guestbook.py
WEBHOOK_URL=""
WEBHOOK_THREAD_ID=""
# End configuration for Discord Webhook

[GSheets]
# This is derived from your service_account.json, so you must fill them according to your service account details
# You can find the service_account.json file in your Google Cloud Console
# https://console.cloud.google.com/apis/credentials/serviceaccountkey
type = "service_account"
project_id = "your-project-id"
private_key_id = "your-private-key-id"
private_key = "your-private-key"
client_email = "your-client-email"
client_id = "your-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "your-client-x509-cert-url"

